Traceback (most recent call last):
  File "train.py", line 214, in <module>
    train(args)
  File "train.py", line 100, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/Code/Code/dataset.py", line 23, in __getitem__
    patch = np.load(file_path)
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-tmp/preprocessed_data/augmanted/positives/1.3.6.1.4.1.14519.5.2.1.6279.6001.148229375703208214308676934766_0_0.npy'